version: '3.9'

services:
  backend:
    build: ./
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8080:8080"
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: "haziorvos"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
      - /run/postgresql
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: